name: 'Aqua find defect key'
description: 'Find defect keys in commit messages or branch names.'
branding:
  icon: 'droplet'
  color: 'blue'
inputs:
  aqua-base-url:
    description: 'Base url for aqua rest api'
    required: true
    default: 'https://aqua-saas2.andagon.com/aquaWebNG/api'
  aqua-token:
    description: 'Bearer token for authentication against aqua cloud instance'
    required: true
  from:
    description: 'Provide a string to search for defect keys.'
    required: true
outputs:
  defect:
    description: 'Key of the found defect key. If more than one are found, than the first one is returned.'
runs:
  using: 'node12'
  main: 'dist/index.js'
