on: push
name: Test on push
jobs:
  addComment:
    name: search for defect keys on different sources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login to aqua saas instance
        id: login
        uses: aqua-github-actions/ga-aqua-login@v1.0.1
        env:
          AQUA_USERNAME: ${{ secrets.AQUA_USERNAME }}
          AQUA_PASSWORD: ${{ secrets.AQUA_PASSWORD }}
      - name: find defect key on commits
        uses: ./
        env:
          NODE_DEBUG: http, net, stream
        with:
          aqua-token: ${{ steps.login.outputs.token }}
          from: commits
      - name: find defect key on branch name
        uses: ./
        env:
          NODE_DEBUG: http, net, stream
        with:
          aqua-token: ${{ steps.login.outputs.token }}
          from: branch
      - name: find defect key on static string
        id: defect-key
        uses: ./
        env:
          NODE_DEBUG: http, net, stream
        with:
          aqua-token: ${{ steps.login.outputs.token }}
          from: This is a defect key DF001268
      - name: show founded defect key
        run: echo ${{ steps.defect-key.outputs.defect }}
      - name: logout to aqua saas instance
        uses: aqua-github-actions/ga-aqua-logout@v1.0.0
        with:
          aqua-token: ${{ steps.login.outputs.token }}